"""Provider-neutral contracts shared by external-information adapters."""

from .errors import ContractViolation

from .identity import (
    ContentIdentity,
    IdempotencyClassification,
    RevisionRelationship,
    StableIdentity,
    StableIdentityKind,
    classify_idempotency,
)
from .fact_store import (
    DerivedMetric,
    Evidence,
    EvidenceKind,
    EvidenceQuality,
    Fact,
    FactAssertionKind,
    FactStoreRecord,
    Interpretation,
    InterpretationAssertionKind,
    RecordEnvelope,
    RecordType,
    Relationship,
    RelationshipAssertionKind,
    RelationshipDirection,
    RetentionClass,
    records_available_as_of,
    validate_fact_store,
)
from .cross_market import (
    CrossMarketHypothesis,
    FxDirectionConsistency,
    HypothesisConfidence,
    ProposedFlowDirection,
)
from .macro_market import MacroMarketObservation, MacroMarketRegion, MacroMarketSeriesKind
from .market_relationship import MarketRelationshipContext, MarketRelationshipKind
from .market_reaction import (
    MarketReactionAssessment,
    MarketReactionConfidence,
    MarketReactionInterpretationType,
)
from .repricing_state import (
    RepricingState,
    RepricingStateAssessment,
    is_allowed_repricing_transition,
)
from .earnings import (
    AccountingBasis,
    EarningsEvent,
    EarningsEventKind,
    EarningsEvidenceRef,
    EarningsEvidenceRole,
    EarningsResultMetric,
    ScheduledReleaseWindow,
)

from .checkpoint import (
    AcquisitionCheckpoint,
    BoundedWindow,
    CheckpointError,
    CheckpointScope,
    CheckpointState,
    OpaqueCursor,
)
from .provider import (
    AdapterItem,
    AdapterPage,
    AdapterRequest,
    ErrorInfo,
    assert_page_contract,
    assert_adapter_item_contract,
    assert_secret_free,
    checkpoint_for_page,
    classify_adapter_item,
    collect_pages,
)
from .provenance import (
    ContentHash,
    Provenance,
    ProviderRevision,
    SourceReference,
    SourceTimestamp,
    TimestampPrecision,
)
from .temporary_content import TemporaryContent, TemporaryContentState, validate_temporary_content

__all__ = [
    "AccountingBasis",
    "AcquisitionCheckpoint",
    "AdapterPage",
    "AdapterItem",
    "AdapterRequest",
    "BoundedWindow",
    "ContentIdentity",
    "CheckpointScope",
    "CheckpointError",
    "CheckpointState",
    "ContractViolation",
    "CrossMarketHypothesis",
    "EarningsEvent",
    "EarningsEventKind",
    "EarningsEvidenceRef",
    "EarningsEvidenceRole",
    "EarningsResultMetric",
    "ErrorInfo",
    "Evidence",
    "EvidenceKind",
    "EvidenceQuality",
    "Fact",
    "FactAssertionKind",
    "FactStoreRecord",
    "FxDirectionConsistency",
    "HypothesisConfidence",
    "IdempotencyClassification",
    "Interpretation",
    "InterpretationAssertionKind",
    "MacroMarketObservation",
    "MacroMarketRegion",
    "MacroMarketSeriesKind",
    "MarketReactionAssessment",
    "MarketReactionConfidence",
    "MarketReactionInterpretationType",
    "MarketRelationshipContext",
    "MarketRelationshipKind",
    "OpaqueCursor",
    "ProposedFlowDirection",
    "RepricingState",
    "RepricingStateAssessment",
    "ScheduledReleaseWindow",
    "assert_page_contract",
    "assert_adapter_item_contract",
    "assert_secret_free",
    "checkpoint_for_page",
    "classify_adapter_item",
    "collect_pages",
    "ContentHash",
    "Provenance",
    "ProviderRevision",
    "RecordEnvelope",
    "RecordType",
    "Relationship",
    "RelationshipAssertionKind",
    "RelationshipDirection",
    "RetentionClass",
    "RevisionRelationship",
    "SourceReference",
    "SourceTimestamp",
    "StableIdentity",
    "StableIdentityKind",
    "TimestampPrecision",
    "TemporaryContent",
    "TemporaryContentState",
    "validate_temporary_content",
    "classify_idempotency",
    "DerivedMetric",
    "is_allowed_repricing_transition",
    "records_available_as_of",
    "validate_fact_store",
]
