"""Provider-neutral contracts shared by external-information adapters."""

from .errors import ContractViolation

from .identity import (
    ContentIdentity,
    IdempotencyClassification,
    RevisionRelationship,
    StableIdentity,
    StableIdentityKind,
    classify_idempotency,
)
from .fact_store import (
    DerivedMetric,
    Evidence,
    EvidenceKind,
    EvidenceQuality,
    Fact,
    FactAssertionKind,
    FactStoreRecord,
    Interpretation,
    InterpretationAssertionKind,
    RecordEnvelope,
    RecordType,
    Relationship,
    RelationshipAssertionKind,
    RelationshipDirection,
    RetentionClass,
    records_available_as_of,
    validate_fact_store,
)

from .checkpoint import (
    AcquisitionCheckpoint,
    BoundedWindow,
    CheckpointError,
    CheckpointScope,
    CheckpointState,
    OpaqueCursor,
)
from .provider import (
    AdapterPage,
    AdapterRequest,
    ErrorInfo,
    assert_page_contract,
    assert_secret_free,
    collect_pages,
)
from .provenance import (
    ContentHash,
    Provenance,
    ProviderRevision,
    SourceReference,
    SourceTimestamp,
    TimestampPrecision,
)

__all__ = [
    "AcquisitionCheckpoint",
    "AdapterPage",
    "AdapterRequest",
    "BoundedWindow",
    "ContentIdentity",
    "CheckpointScope",
    "CheckpointError",
    "CheckpointState",
    "ContractViolation",
    "ErrorInfo",
    "Evidence",
    "EvidenceKind",
    "EvidenceQuality",
    "Fact",
    "FactAssertionKind",
    "FactStoreRecord",
    "IdempotencyClassification",
    "Interpretation",
    "InterpretationAssertionKind",
    "OpaqueCursor",
    "assert_page_contract",
    "assert_secret_free",
    "collect_pages",
    "ContentHash",
    "Provenance",
    "ProviderRevision",
    "RecordEnvelope",
    "RecordType",
    "Relationship",
    "RelationshipAssertionKind",
    "RelationshipDirection",
    "RetentionClass",
    "RevisionRelationship",
    "SourceReference",
    "SourceTimestamp",
    "StableIdentity",
    "StableIdentityKind",
    "TimestampPrecision",
    "classify_idempotency",
    "DerivedMetric",
    "records_available_as_of",
    "validate_fact_store",
]
