"""Official-source registry and downstream official-context helpers."""

from .feed_adapter import (
    OFFICIAL_FEED_PROFILES,
    OfficialAcquisitionRoute,
    OfficialDiscoveredItem,
    OfficialFeedCheckpoint,
    OfficialFeedPage,
    OfficialFeedProfile,
    OfficialFeedStatus,
    OfficialItemAvailability,
    classify_item_change,
    get_official_feed_profile,
)
from .official_statement import (
    OfficialPolicyFactBundle,
    OfficialPolicyFactKind,
    OfficialPolicyObservation,
    build_official_policy_fact,
    build_official_policy_facts,
)
from .registry import (
    OFFICIAL_ACTORS,
    OFFICIAL_SOURCES,
    ContentActorMode,
    OfficialActor,
    OfficialActorKind,
    OfficialSource,
    OfficialSourceLane,
    OfficialSourceType,
    get_official_actor,
    get_official_source,
    validate_official_registry,
)
from .relevance import (
    AMD_INSTRUMENT_ID,
    NVDA_INSTRUMENT_ID,
    SEMICONDUCTOR_THEME_ID,
    ActionBasis,
    IdentityBasis,
    OfficialRelevanceBundle,
    OfficialRelevanceClass,
    OfficialRelevanceObservation,
    OfficialRelevanceTargetType,
    build_official_relevance,
    build_official_relevances,
)

__all__ = [
    "OFFICIAL_ACTORS",
    "OFFICIAL_SOURCES",
    "OFFICIAL_FEED_PROFILES",
    "AMD_INSTRUMENT_ID",
    "NVDA_INSTRUMENT_ID",
    "SEMICONDUCTOR_THEME_ID",
    "ActionBasis",
    "ContentActorMode",
    "IdentityBasis",
    "OfficialActor",
    "OfficialActorKind",
    "OfficialSource",
    "OfficialSourceLane",
    "OfficialSourceType",
    "OfficialAcquisitionRoute",
    "OfficialDiscoveredItem",
    "OfficialFeedCheckpoint",
    "OfficialFeedPage",
    "OfficialFeedProfile",
    "OfficialFeedStatus",
    "OfficialItemAvailability",
    "OfficialPolicyFactBundle",
    "OfficialPolicyFactKind",
    "OfficialPolicyObservation",
    "OfficialRelevanceBundle",
    "OfficialRelevanceClass",
    "OfficialRelevanceObservation",
    "OfficialRelevanceTargetType",
    "build_official_policy_fact",
    "build_official_policy_facts",
    "build_official_relevance",
    "build_official_relevances",
    "classify_item_change",
    "get_official_actor",
    "get_official_source",
    "get_official_feed_profile",
    "validate_official_registry",
]
