"""Provider-neutral News acquisition and extraction helpers for the local Corporate Canary."""

from .alpaca import (
    ALPACA_NEWS_PROVIDER_KEY,
    AlpacaNewsAdapter,
    AlpacaNewsRequestFailure,
    AlpacaNewsTransport,
    NewsArticleMetadata,
    decode_alpaca_news_timestamp,
)
from .body import (
    AlpacaNewsBodyAccessor,
    NewsBodyAcquisition,
    NewsBodyTransport,
    TemporaryBodyStore,
    exception_record,
)
from .body_extraction import (
    NEWS_BODY_EVIDENCE_SCHEMA_VERSION,
    NEWS_BODY_EXTRACTOR_NAME,
    NEWS_BODY_EXTRACTOR_VERSION,
    NEWS_BODY_FACT_SCHEMA_VERSION,
    BodyEvidenceSpan,
    BodyExtractionBatch,
    BodyFactCandidate,
    TemporaryBodyReader,
    extract_body_fact_candidates,
)
from .deterministic_extraction import (
    NEWS_DETERMINISTIC_EXTRACTOR_VERSION,
    NEWS_EVENT_EVIDENCE_SCHEMA_VERSION,
    NEWS_EVENT_FACT_SCHEMA_VERSION,
    HeadlinePattern,
    NewsFactCandidate,
    extract_headline_fact_candidates,
    headline_patterns,
)
from .duplicate import (
    NewsArticleComparison,
    NewsArticleComparisonKind,
    canonicalize_news_url,
    compare_news_articles,
)
from .event_taxonomy import (
    NEWS_EVENT_TAXONOMY_VERSION,
    EventTaxonomyEntry,
    NewsEventType,
    event_taxonomy_entry,
    news_event_taxonomy,
)
from .recall import (
    NEWS_RECALL_EVALUATOR_VERSION,
    NEWS_RECALL_REPORT_SCHEMA_VERSION,
    NewsRecallDiscovery,
    NewsRecallReferenceEvent,
    NewsRecallReferenceResult,
    NewsRecallReport,
    evaluate_news_recall,
)
from .retention import (
    NEWS_RETENTION_CONTROLLER_VERSION,
    RetentionDecision,
    TemporaryContentDeleter,
    assert_exception_retention_compliant,
    delete_due_content,
    retention_decision,
)
from .review import (
    NEWS_REVIEW_METHOD_VERSION,
    NEWS_REVIEW_RESOLUTION_SCHEMA_VERSION,
    NEWS_REVIEW_SCHEMA_VERSION,
    NewsReviewCase,
    NewsReviewReasonKind,
    NewsReviewResolution,
    open_news_review_case,
    resolve_news_review_case,
)

__all__ = [
    "ALPACA_NEWS_PROVIDER_KEY",
    "AlpacaNewsAdapter",
    "AlpacaNewsBodyAccessor",
    "AlpacaNewsRequestFailure",
    "AlpacaNewsTransport",
    "BodyEvidenceSpan",
    "BodyExtractionBatch",
    "BodyFactCandidate",
    "EventTaxonomyEntry",
    "HeadlinePattern",
    "NEWS_BODY_EVIDENCE_SCHEMA_VERSION",
    "NEWS_BODY_EXTRACTOR_NAME",
    "NEWS_BODY_EXTRACTOR_VERSION",
    "NEWS_BODY_FACT_SCHEMA_VERSION",
    "NEWS_DETERMINISTIC_EXTRACTOR_VERSION",
    "NEWS_EVENT_EVIDENCE_SCHEMA_VERSION",
    "NEWS_EVENT_FACT_SCHEMA_VERSION",
    "NEWS_EVENT_TAXONOMY_VERSION",
    "NEWS_RECALL_EVALUATOR_VERSION",
    "NEWS_RECALL_REPORT_SCHEMA_VERSION",
    "NEWS_RETENTION_CONTROLLER_VERSION",
    "NEWS_REVIEW_METHOD_VERSION",
    "NEWS_REVIEW_RESOLUTION_SCHEMA_VERSION",
    "NEWS_REVIEW_SCHEMA_VERSION",
    "NewsArticleComparison",
    "NewsArticleComparisonKind",
    "NewsArticleMetadata",
    "NewsBodyAcquisition",
    "NewsBodyTransport",
    "NewsEventType",
    "NewsFactCandidate",
    "NewsRecallDiscovery",
    "NewsRecallReferenceEvent",
    "NewsRecallReferenceResult",
    "NewsRecallReport",
    "NewsReviewCase",
    "NewsReviewReasonKind",
    "NewsReviewResolution",
    "RetentionDecision",
    "TemporaryBodyReader",
    "TemporaryBodyStore",
    "TemporaryContentDeleter",
    "assert_exception_retention_compliant",
    "canonicalize_news_url",
    "compare_news_articles",
    "decode_alpaca_news_timestamp",
    "delete_due_content",
    "evaluate_news_recall",
    "event_taxonomy_entry",
    "exception_record",
    "extract_body_fact_candidates",
    "extract_headline_fact_candidates",
    "headline_patterns",
    "news_event_taxonomy",
    "open_news_review_case",
    "resolve_news_review_case",
    "retention_decision",
]
